### ISSUE TITLE
Week 1 Materials - Course Intro & HTML, CSS

### ISSUE THREAD

**Issue by RyanKor** [RyanKor/vietnam_bootcamp#1]
**Week 1 - Curriculum Intro, Core Explanation of Web Structure, HTML & CSS, git**
 공부한 내용은 항상 깃 블로그에 정리하는 형태로 과제 제작하기
    - Mon -> Curriculum Intro (0.5), Goal of the Course(0.5), Ground Rules(0.5), Self-Introduction(0.5), Core Explanation of Web Structure(1), HTML Explanation(2), CSS Explanation 1 (1), Terminal Settings(widow&IOS, 1), Install IDE & Manual Explanation & chrome developer tools (window&IOS, 1), Daily Quiz(Assignment) → 생활코딩 강좌 참고
    - Tue -> Assignment Check(1), CSS explanation2(1), Git Explanation(1), Install Git / Github Signup / git process(making a repository, add, commit, pull, push) (2), git page deployment(1), Making Google.com main page using HTML & CSS (2)
    - Wed -> assignment check(HTML&CSS 사용해서 본인 관심사 깃블로그 업로드, 1), Bootstrap explanation(1), bootstrap practice(3), RWD(Responsive Web Design) CSS(2), Designing web page using bootstrap(1)
    - Thur -> assignment check(1), Navbar/Footer/Form Tag(2),  Making a Documentation page with HTML & CSS including(3), Landing Page(ref:wix, 1), 1시간 교육 자료 추가 필요
    - Fri -> assignment check(1), Weekly Repetition (Making Instagram with HTML & CSS, 3), advanced css(animation, 2), 2시간 교육 자료 추가 필요

HTML & CSS reference : https://medium.com/@avicndugu/projects-to-practice-html-css-skills-for-beginners-8b9ed67a7dd1

모든 강의안은 강의자가 없을 때 수강자가 강의 자료만 보고도 따라 칠 수 있을 정도로 자세하게!

**Comment by RyanKor** [comment]
재정리

- Curriculum Intro
- The goal of the Course
- Ground Rules
- Self-Intro
- Core Explanation of Web Structure
- HTML Explanation
- CSS Explanation
- Terminal Settings
- IDE & Chrome Developer tools
- Git (installation, explanation, Github Signup, Process)
- Git page deployment
- Bootstrap
- RWD
- Navbar/Footer/Form Tag
- Advanced CSS
- Assignment(퀴즈, 구글 메인 페이지 제작, 부트 스트랩 활용한 페이지 제작, 랜딩 페이지 만들기, 인스타그램)

**Comment by MC-likelion07** [comment]
1. 인스타그램 만들기
	: flexbox부분이 들어가는 것으로 알고있는데, flexbox에 대해서도 다루어야 할 것.
	(참고자료 : https://lshdv.tistory.com/2?category=827616 - 인스타그램 따라하기 - 커리큘럼 참고 자료 정리에 추가 완료)
	
	2. resume 만들기
	: 정적 웹페이지 만들 때 assignment로 들어가는 것도 괜찮을 것 같다. (html파일과 css만 간단히 수정해서 github page로 배포하면 됨)
	(참고자료 : https://startbootstrap.com/previews/resume/) 
	
	3. 수요일 bootstrap practice 3시간은 조금 많지 않나라는 생각이 든다. (길어도 2시간이면 괜찮을거 같다.) 그 시간에 RWD를 1시간 더 늘리는게 좋을거 같다.
참고자료(https://developers.google.com/web/fundamentals/design-and-ux/responsive?hl=ko : 커리큘럼 참고 자료 정리에 추가 완료)

**Comment by RyanKor** [comment]
> ```
> 1. 인스타그램 만들기
> : flexbox부분이 들어가는 것으로 알고있는데, flexbox에 대해서도 다루어야 할 것.
> (참고자료 : https://lshdv.tistory.com/2?category=827616 - 인스타그램 따라하기 - 커리큘럼 참고 자료 정리에 추가 완료)
> 
> 2. resume 만들기
> : 정적 웹페이지 만들 때 assignment로 들어가는 것도 괜찮을 것 같다. (html파일과 css만 간단히 수정해서 github page로 배포하면 됨)
> (참고자료 : https://startbootstrap.com/previews/resume/) 
> 
> 3. 수요일 bootstrap practice 3시간은 조금 많지 않나라는 생각이 든다. (길어도 2시간이면 괜찮을거 같다.) 그 시간에 RWD를 1시간 더 늘리는게 좋을거 같다.
> ```
> 
> (참고자료(https://developers.google.com/web/fundamentals/design-and-ux/responsive?hl=ko : 커리큘럼 참고 자료 정리에 추가 완료)

2. resume 만들기 괜찮네요! 금방 만들 것 같고, 본인들이 관리하기도 좋을 것 같습니다.
