### ISSUE TITLE
Week 2 Materials - Python

### ISSUE THREAD

**Issue by RyanKor** [RyanKor/vietnam_bootcamp#2]
- Week 2 - Python
 파이썬 가르쳐 줄 때, vending machine을 구현한다고 하면 자판기가 작동하는 프로세스에 대해 쭉 설명하듯 힌트를 주고, 코드를 작성하는 시간을 충분히 주는 것이 중요함.
    - Mon -> assignment check(1), Weekly Review(1), Install & Explanation Python and Virtual Environment(1.5), python data types / for&while / Condition States(if/else, 2), assignment (2, 가위, 바위 보) -> 7.5시간 충분
    - Tue -> assignment check(1), python function / module / class(3), assignment (2, making a calculator) -> 2시간 채워야함
    - Wed -> assignment check(1), python library(1), requests(POST, GET, PUT, DELET) / http / response(3), assignment(2, url 갖고 놀기 ref 참고) -> 1시간 채워야함
    - Thur -> assignment check(1), crawling using bs4 / selenium(4), assignment(2, crawling google) --> 1시간 채워야함
    - Fri -> assignment check(1), Building a Study Group(1, Team), Brief Explanation of Programming Cooperation(1),  assignment(2, vending machine 만들기) -> 2시간 채워야함

**Comment by RyanKor** [comment]
요일별로 시간을 지정해 가르치는 방안보다 일주일 동안 무슨 내용을 얼마나 가르칠 것인지 지정하는 방향으로 가보는 것이 어떨까 생각함.

- Weekly Review
- Install & Explanation Python and Virtual Environment
- Basic Explanation of Python
- Python Libraries
- python request(POST, GET, PUT, DELETE) / Http / Response
- Crawling(bs4, selenium)
- Making Study Group
- Basic Explanation of Programming Cooperation
- Assignment(가위바위보, 계산기, url에 요청, 응답 주고 받기, 구글 크롤링, 자판기 프로그래밍)

**Comment by MC-likelion07** [comment]
1. python data types의 범위는? - 기본 자료형(문자열, 정수 등), 리스트, 딕셔너리, 튜플, 셋
	자료형(data types)과 제어문, 반복문을 설명하는데 2시간이 살짝 부족할거 같기도 하다.
	ㄴ 기본 자료형을 남기고 파이썬의 자료구조(리스트, 딕셔너리, 튜플, 셋)를 화요일의 남는 시간에 해당 부분을 넣어보는 것도 좋을 듯
	ㄴ 시간이 된다면 파이썬과 js가 겹치는 부분을 포함하는 것도 좋을 듯(기본 자료형, 제어문, 반복문 정도만)
	
	Python OOP의 범위는 어디까지로 할 것인가? (추상화, 캡슐화, 상속성, 다형성)
