### ISSUE TITLE
Week 8 Materials (Team Projects)

### ISSUE THREAD

**Issue by RyanKor** [RyanKor/vietnam_bootcamp#8]
2주 동안 학생들이 모여서 개발할 수 있는 환경을 제공하는 것만으로도 큰 도움이 된다.

- Building Team Ideas (developing a product plan for two weeks)
- 1 on 1 Mentoring to each team

**Comment by RyanKor** [comment]
학생들이 따로 모여서 개발할 자리를 만드는 것은 부트캠프 팀 프로젝트 주간에는 좋지 못한 전략이다.

아침부터 밤까지 학생들과 함께 보조하면서 개발하는 느낌으로 접근하는 것이 좋다 (물론 토,일 공휴일 제외)

아이디어를 발전시키는 방향에서부터 도움을 주되, 스스로 만들 수 있게 도와줘야된다.

**Comment by MC-likelion07** [comment]
1. 프로젝트를 진행하기 이전에 만들어보고 싶은 웹사이트에 대한 아이디어를 생각할 여유를 충분히 준다.

2. 프로젝트에 평가기준이 있으면 좀 더 나은 결과물이 나올 수도 있을것같다.

**Comment by RyanKor** [comment]
(프로젝트 운영 관련 방침 생각)
Bootcamp 전반적으로 pair programming이 들어가야하지만, 수업 중에는 페어 프로그래밍 보다 강의가 우선되야하고, 프로젝트 주간에 페어 프로그래밍을 중점적으로 도와줘야한다.
